// <auto-generated />
using System;
using CollabTask.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollabTask.Api.Migrations
{
    [DbContext(typeof(CollabTaskDbContext))]
    [Migration("20251213080048_AddTaskAttachments")]
    partial class AddTaskAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollabTask.Api.Models.ActivityLog", b =>
                {
                    b.Property<Guid>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Comment", b =>
                {
                    b.Property<Guid>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TaskID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentID");

                    b.HasIndex("TaskID");

                    b.HasIndex("UserID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("RelatedEntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CollabTask.Api.Models.SystemRole", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("SystemRoles");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("WorkspaceID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagID");

                    b.HasIndex("WorkspaceID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Task", b =>
                {
                    b.Property<Guid>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstimatedTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("WorkspaceID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TaskID");

                    b.HasIndex("CreatorUserID");

                    b.HasIndex("WorkspaceID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CollabTask.Api.Models.TaskAssignment", b =>
                {
                    b.Property<Guid>("TaskID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("AssigneeUserID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("ApprovalNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssignerUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletionRequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TaskID", "AssigneeUserID");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("AssigneeUserID");

                    b.HasIndex("AssignerUserID");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("CollabTask.Api.Models.TaskAssignmentHistory", b =>
                {
                    b.Property<Guid>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ActionByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssigneeUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PreviousAssigneeUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TaskID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HistoryID");

                    b.HasIndex("ActionByUserID");

                    b.HasIndex("AssigneeUserID");

                    b.HasIndex("PreviousAssigneeUserID");

                    b.HasIndex("TaskID");

                    b.ToTable("TaskAssignmentHistories");
                });

            modelBuilder.Entity("CollabTask.Api.Models.TaskAttachment", b =>
                {
                    b.Property<Guid>("AttachmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TaskID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AttachmentID");

                    b.HasIndex("TaskID");

                    b.HasIndex("UploadedByUserID");

                    b.ToTable("TaskAttachments");
                });

            modelBuilder.Entity("CollabTask.Api.Models.TaskTag", b =>
                {
                    b.Property<Guid>("TaskID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<int>("TagID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("TaskID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("TaskTags");
                });

            modelBuilder.Entity("CollabTask.Api.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarURL")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemRoleID")
                        .HasColumnType("int");

                    b.Property<Guid?>("TaskWeightsUserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserID");

                    b.HasIndex("SystemRoleID");

                    b.HasIndex("TaskWeightsUserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CollabTask.Api.Models.UserTaskCompletionLog", b =>
                {
                    b.Property<long>("InteractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InteractionID"));

                    b.Property<DateTime>("CompletedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DeadlineScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("EffortScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ImportanceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("TaskID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("WasSuggested")
                        .HasColumnType("bit");

                    b.HasKey("InteractionID");

                    b.HasIndex("TaskID");

                    b.HasIndex("UserID");

                    b.ToTable("UserInteractionsForAI", (string)null);
                });

            modelBuilder.Entity("CollabTask.Api.Models.UserTaskWeight", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DeadlineWeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("EffortWeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ImportanceWeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.ToTable("UserTaskWeights");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Workspace", b =>
                {
                    b.Property<Guid>("WorkspaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("bit");

                    b.Property<Guid>("OwnerUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorkspaceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("WorkspaceID");

                    b.HasIndex("OwnerUserID");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("CollabTask.Api.Models.WorkspaceMember", b =>
                {
                    b.Property<Guid>("WorkspaceID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WorkspaceID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("WorkspaceMembers");
                });

            modelBuilder.Entity("CollabTask.Api.Models.ActivityLog", b =>
                {
                    b.HasOne("CollabTask.Api.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Comment", b =>
                {
                    b.HasOne("CollabTask.Api.Models.Task", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollabTask.Api.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Notification", b =>
                {
                    b.HasOne("CollabTask.Api.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Tag", b =>
                {
                    b.HasOne("CollabTask.Api.Models.Workspace", "Workspace")
                        .WithMany("Tags")
                        .HasForeignKey("WorkspaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Task", b =>
                {
                    b.HasOne("CollabTask.Api.Models.User", "Creator")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatorUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollabTask.Api.Models.Workspace", "Workspace")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkspaceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("CollabTask.Api.Models.TaskAssignment", b =>
                {
                    b.HasOne("CollabTask.Api.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CollabTask.Api.Models.User", "Assignee")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("AssigneeUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollabTask.Api.Models.User", "Assigner")
                        .WithMany()
                        .HasForeignKey("AssignerUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollabTask.Api.Models.Task", "Task")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Assignee");

                    b.Navigation("Assigner");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CollabTask.Api.Models.TaskAssignmentHistory", b =>
                {
                    b.HasOne("CollabTask.Api.Models.User", "ActionBy")
                        .WithMany()
                        .HasForeignKey("ActionByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollabTask.Api.Models.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollabTask.Api.Models.User", "PreviousAssignee")
                        .WithMany()
                        .HasForeignKey("PreviousAssigneeUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CollabTask.Api.Models.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionBy");

                    b.Navigation("Assignee");

                    b.Navigation("PreviousAssignee");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CollabTask.Api.Models.TaskAttachment", b =>
                {
                    b.HasOne("CollabTask.Api.Models.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollabTask.Api.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("CollabTask.Api.Models.TaskTag", b =>
                {
                    b.HasOne("CollabTask.Api.Models.Tag", "Tag")
                        .WithMany("TaskTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollabTask.Api.Models.Task", "Task")
                        .WithMany("TaskTags")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CollabTask.Api.Models.User", b =>
                {
                    b.HasOne("CollabTask.Api.Models.SystemRole", "SystemRole")
                        .WithMany("Users")
                        .HasForeignKey("SystemRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollabTask.Api.Models.UserTaskWeight", "TaskWeights")
                        .WithMany()
                        .HasForeignKey("TaskWeightsUserID");

                    b.Navigation("SystemRole");

                    b.Navigation("TaskWeights");
                });

            modelBuilder.Entity("CollabTask.Api.Models.UserTaskCompletionLog", b =>
                {
                    b.HasOne("CollabTask.Api.Models.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollabTask.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollabTask.Api.Models.UserTaskWeight", b =>
                {
                    b.HasOne("CollabTask.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Workspace", b =>
                {
                    b.HasOne("CollabTask.Api.Models.User", "Owner")
                        .WithMany("OwnedWorkspaces")
                        .HasForeignKey("OwnerUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CollabTask.Api.Models.WorkspaceMember", b =>
                {
                    b.HasOne("CollabTask.Api.Models.User", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollabTask.Api.Models.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("CollabTask.Api.Models.SystemRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Tag", b =>
                {
                    b.Navigation("TaskTags");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Task", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("TaskAssignments");

                    b.Navigation("TaskTags");
                });

            modelBuilder.Entity("CollabTask.Api.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Comments");

                    b.Navigation("CreatedTasks");

                    b.Navigation("Notifications");

                    b.Navigation("OwnedWorkspaces");

                    b.Navigation("TaskAssignments");

                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("CollabTask.Api.Models.Workspace", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Tags");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
